environment_config:
  path: environment_config.dart # optional, result file path against `lib/` folder
  dotenv_path: .env # optional, result file path for .env file against project root folder
  class: EnvironmentConfig # optional, class name
  fields: # set of fields for command
    environment: # key name
      default: 'development'
      env_var:  'F_APP_ENVIRONMENT'
    futurama_api_url:
      default: ''
      env_var:  'FUTURAMA_API_URL'
    omdb_api_url:
      default: ''
      env_var:  'OMDB_API_URL'
    omdb_api_key:
      default: ''
      env_var:  'OMDB_API_KEY'
